version: '3'
services:
  uniclogs-cesium:
    image: uniclogs-cesium
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    network_mode: 'host'
    volumes:
      - ./data:/data
